services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    networks:
      romm-network:
        ipv4_address: 172.22.0.20
    security_opt:
      - "label=disable"
    environment:
      - HOSTNAME=romm
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME} # Should match MARIADB_DATABASE in mariadb
      - DB_USER=${DB_USER} # Should match MARIADB_USER in mariadb
      - DB_PASSWD=${DB_PASSWD} # Should match MARIADB_PASSWORD in mariadb
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY} # Generate a key with `openssl rand -hex 32`
      - SCREENSCRAPER_USER=${SCREENSCRAPER_USER} # These are the recommended metadata providers
      - SCREENSCRAPER_PASSWORD=${SCREENSCRAPER_PASSWORD} # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#screenscraper
      - RETROACHIEVEMENTS_API_KEY=${RETROACHIEVEMENTS_API_KEY} # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#retroachievements
      - STEAMGRIDDB_API_KEY=${STEAMGRIDDB_API_KEY} # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#steamgriddb
      - HASHEOUS_API_ENABLED=${HASHEOUS_API_ENABLED} # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#hasheous
    volumes:
      - ./romm/romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - ./romm/romm_redis_data:/redis-data # Cached data for background tasks
      - ./romm/assets:/romm/assets # Uploaded saves, states, etc.
      - ./romm/config:/romm/config # (Optional) Path where config.yml is stored
      #Rom Libaries
      - ${Apple_Mac_PATH}:/romm/library/Apple_Mac
      - ${Apple_IOS_PATH}:/romm/library/Apple_IOS
      - ${Apple_Bandai_Pippin_PATH}:/romm/library/Apple_Bandai_Pippin
      - ${Apple_II_PATH}:/romm/library/Apple_II
      #Google Paths
      - ${Google_Android_PATH}:/romm/library/Android
      #Microsoft PATHS
      - ${Microsoft_DOS_PATH}:/romm/library/DOS
      - ${Microsoft_Windows_PATH}:/romm/library/Windows
      - ${Microsoft_XBOX_PATH}:/romm/library/XBOX
      - ${Microsoft_Xbox_360_PATH}:/romm/library/Xbox_360
      #Nintendo Paths
      - ${Nintendo_Gameboy_PATH}:/romm/library/Gameboy
      - ${Nintendo_Gameboy_Advance_PATH}:/romm/library/Gameboy_Advance
      - ${Nintendo_Gameboy_Color_PATH}:/romm/library/Gameboy_Color
      - ${Nintendo_NES_PATH}:/romm/library/NES
      - ${Nintendo_N64_PATH}:/romm/library/N64
      - ${Nintendo_3DS_PATH}:/romm/library/3DS
      - ${Nintendo_New_3DS_PATH}:/romm/library/New_3DS
      - ${Nintendo_DS_PATH}:/romm/library/DS
      - ${Nintendo_GameCube_PATH}:/romm/library/GameCube
      - ${Nintendo_Pokemon_Mini_PATH}:/romm/library/Pokemon_Mini
      - ${Nintendo_SNES_PATH}:/romm/library/SNES
      - ${Nintendo_Switch_PATH}:/romm/library/Switch
      - ${Nintendo_Virtual_Boy_PATH}:/romm/library/Virtual_Boy
      - ${Nintendo_Wii_PATH}:/romm/library/Wii
      - ${Nintendo_Wii_U_PATH}:/romm/library/Wii_U
      #Sony Paths
      - ${Sony_PlayStation_PATH}:/romm/library/PlayStation
      - ${Sony_PlayStation_2_PATH}:/romm/library/PlayStation_2
      - ${Sony_PlayStation_3_PATH}:/romm/library/PlayStation_3
      - ${Sony_PlayStation_4_PATH}:/romm/library/PlayStation_4
      - ${Sony_PlayStation_5_PATH}:/romm/library/PlayStation_5
      - ${Sony_PlayStation_Portable_PATH}:/romm/library/PlayStation_Portable
      - ${Sony_PlayStation_Vita_PATH}:/romm/library/PlayStation_Vita
      #SEGA PATHS
      - ${SEGA_Dreamcast_PATH}:/romm/library/Dreamcast
      - ${SEGA_Game_Gear_PATH}:/romm/library/Game_Gear
      - ${SEGA_Master_System_PATH}:/romm/library/Master_System
      - ${SEGA_Mega_Drive_PATH}:/romm/library/Mega_Drive
      - ${SEGA_Pico_PATH}:/romm/library/Pico
      - ${SEGA_Saturn_PATH}:/romm/library/Saturn
      - ${SEGA_SG-1000_PATH}:/romm/library/SG-1000
    #ports:
    #  - 80:8080
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - HOSTNAME=romm-db
      - MARIADB_ROOT_PASSWORD= # Use a unique, secure password
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWD}
    volumes:
      - ./romm/mysql_data:/var/lib/mysql
    security_opt:
      - "label=disable"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  romm-network:
    driver: bridge
    name: romm-network
    ipam:
      config:
        - subnet: 172.22.0.0/16