services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    networks:
      romm-network:
        ipv4_address: 172.22.0.20
    security_opt:
      - "label=disable"
    environment:
      - HOSTNAME=romm
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME} # Should match MARIADB_DATABASE in mariadb
      - DB_USER=${DB_USER} # Should match MARIADB_USER in mariadb
      - DB_PASSWD=${DB_PASSWD} # Should match MARIADB_PASSWORD in mariadb
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY} # Generate a key with `openssl rand -hex 32`
      - SCREENSCRAPER_USER=${SCREENSCRAPER_USER} # These are the recommended metadata providers
      - SCREENSCRAPER_PASSWORD=${SCREENSCRAPER_PASSWORD} # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#screenscraper
      - RETROACHIEVEMENTS_API_KEY=${RETROACHIEVEMENTS_API_KEY} # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#retroachievements
      - STEAMGRIDDB_API_KEY=${STEAMGRIDDB_API_KEY} # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#steamgriddb
      - HASHEOUS_API_ENABLED=${HASHEOUS_API_ENABLED} # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#hasheous
    volumes:
      - ./romm/romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - ./romm/romm_redis_data:/redis-data # Cached data for background tasks
      - ${LIBRARY_PATH}:/romm/library # Your game library. Check https://docs.romm.app/latest/Getting-Started/Folder-Structure/ for more details.
      - ./romm/assets:/romm/assets # Uploaded saves, states, etc.
      - ./romm/config:/romm/config # (Optional) Path where config.yml is stored
    #ports:
    #  - 80:8080
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - HOSTNAME=romm-db
      - MARIADB_ROOT_PASSWORD= # Use a unique, secure password
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
      - MARIADB_PASSWORD=
    volumes:
      - ./romm/mysql_data:/var/lib/mysql
    security_opt:
      - "label=disable"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  romm-network:
    driver: bridge
    name: romm-network
    ipam:
      config:
        - subnet: 172.22.0.0/16